//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package mp3;

public class Musique extends com.zeroc.Ice.Value
{
    public Musique()
    {
        this.Titre = "";
        this.Artiste = "";
        this.Album = "";
        this.AnneeSortie = "";
        this.Path = "";
    }

    public Musique(String Titre, String Artiste, String Album, String AnneeSortie, String Path)
    {
        this.Titre = Titre;
        this.Artiste = Artiste;
        this.Album = Album;
        this.AnneeSortie = AnneeSortie;
        this.Path = Path;
    }

    public String Titre;

    public String Artiste;

    public String Album;

    public String AnneeSortie;

    public String Path;

    public Musique clone()
    {
        return (Musique)super.clone();
    }

    public static String ice_staticId()
    {
        return "::mp3::Musique";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = 2144514884L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeString(Titre);
        ostr_.writeString(Artiste);
        ostr_.writeString(Album);
        ostr_.writeString(AnneeSortie);
        ostr_.writeString(Path);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        Titre = istr_.readString();
        Artiste = istr_.readString();
        Album = istr_.readString();
        AnneeSortie = istr_.readString();
        Path = istr_.readString();
        istr_.endSlice();
    }
}
